name: test

on:
  push:
    branches:
      - 'feature/*'

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    name: Pre-commit

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run your build and test scripts here.
      - name: Run Terratest
        uses: cloudposse/github-action-terratest@main
        with:
          sourceDir: test
